---
- name: Config Drift
  hosts: all
  gather_facts: no

  tasks:
### Example of showing diffs in check mode ###
    - name: "Show diff between test1.txt & test2.txt" 
      copy:
        src: files/sudoers.config
        dest: /etc/sudoers
      become: yes
      check_mode: yes
      diff: yes

    - name: Fetch Sudoers to compare 
      fetch:
        src: /etc/sudoers
        dest: "{{ playbook_dir }}/temp_sudoers"
        flat: yes
      become: yes

    - name: Diff sudoers file
      command: diff files/sudoers.config {{ playbook_dir }}/temp_sudoers
      register: difference
      delegate_to: localhost
      ignore_errors: yes

    - name: Generate slack response
      template:
        src: slack.j2
        dest: files/response.json
      become: no
      delegate_to: localhost

    - name: Send Slack confirmation
      uri:
        url: "{{response_url}}"
        body: "{{lookup('file', 'files/response.json')}}"
        body_format: json
        method: POST
        validate_certs: no
      become: no
      delegate_to: localhost
      run_once: yes