---
- name: Config Drift
  hosts: rhel
  become: yes
  gather_facts: no
  tasks:
# Example of automatically replacing if file checksum differs ###
    - name: "Make sure the known sudoers file exists at location" 
      copy:
        src: files/sudoers.config
        dest: /etc/sudoers

    - name: Send Slack confirmation
      uri:
        url: "{{response_url}}"
        body: "{'text':'Suoders file is compliant'}"
        body_format: json
        method: POST
        validate_certs: no
      become: no
      delegate_to: localhost
      run_once: yes