---
- name: Config Drift
  hosts: all
  become: yes
  gather_facts: no

  tasks:
### Example of showing diffs in check mode ###
    - name: "Show diff between test1.txt & test2.txt" 
      copy:
        src: files/sudoers.config
        dest: /etc/sudoers
      check_mode: yes
      diff: yes

## Example of automatically replacing if file checksum differs ###
    # - name: "Make sure the known sudoers file exists at location" 
    #   copy:
    #     src: files/sudoers.config
    #     dest: /etc/sudoers
    - debug:
        var: playbook_dir

    - name: Fetch Sudoers to compare 
      fetch:
        src: /etc/sudoers
        dest: "{{ playbook_dir }}/temp_sudoers"
        flat: yes
      delegate_to: localhost
    
    - name: Diff sudoers file
      command: diff files/sudoers.config /tmp/sudoers
      register: difference
      delegate_to: localhost
      ignore_errors: yes
      become: no

    # - name: Generate slack response
    #   template:
    #     src: slack.j2
    #     dest: files/response.json
    #   become: no
    #   delegate_to: localhost

    # - name: Send Slack confirmation
    #   uri:
    #     url: "{{response_url}}"
    #     body: "{{lookup('file', 'files/response.json')}}"
    #     body_format: json
    #     method: POST
    #     validate_certs: no
    #   become: no
    #   delegate_to: localhost
    #   run_once: yes