---
- name: Config Drift
  hosts: stig
  become: yes
  pre_tasks:
    - name: Install EPEL
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
        state: present
        
  roles:
    - role: ansible-security-compliance.rhel7-role-stig-rhel7-disa
      
